'use client';
import Link from 'next/link';
import { useState } from 'react';
export type OrderRow = { id: string; name: string; email: string; phone: string; address: string; product: string; created: number; updated: number; amount: number; state: string; label: string; tracking: string; trackable: boolean };
const badges: Record<string,string> = {waiting:'bg-amber-50 text-amber-800',new:'bg-blue-50 text-blue-700',preparing:'bg-purple-50 text-purple-700',shipped:'bg-emerald-100 text-emerald-800',completed:'bg-slate-100 text-slate-600'};
export function OrderTable({ orders, view }: { orders: OrderRow[]; view: string }) {
  const [query,setQuery]=useState(''); const [status,setStatus]=useState('all'); const [ascending,setAscending]=useState(false); const [detail,setDetail]=useState<string|null>(null);
  const base=orders.filter(o=>view!=='shipping'||o.state!=='waiting');
  const rows=base.filter(o=>(status==='all'||o.state===status)&&[o.id,o.name,o.email,o.product,o.tracking].join(' ').toLowerCase().includes(query.trim().toLowerCase())).sort((a,b)=>ascending?a.updated-b.updated:b.updated-a.updated);
  const money=(amount:number)=>new Intl.NumberFormat('th-TH',{style:'currency',currency:'THB'}).format(amount/100);
  const date=(timestamp:number)=>new Date(timestamp*1000).toLocaleString('th-TH',{timeZone:'Asia/Bangkok',dateStyle:'medium',timeStyle:'short'});
  return <><div className="my-6 grid gap-3 sm:grid-cols-3">{[['ออเดอร์ในชุดนี้',base.length],['รอเตรียม / กำลังเตรียม',base.filter(o=>['new','preparing'].includes(o.state)).length],['จัดส่งแล้ว / เสร็จสิ้น',base.filter(o=>['shipped','completed'].includes(o.state)).length]].map(([label,value])=><div key={label} className="rounded-xl border border-slate-200 bg-white px-5 py-4"><p className="text-xs text-slate-500">{label}</p><p className="mt-2 text-2xl font-semibold text-slate-800">{value}</p></div>)}</div>
  <div className="mb-5 flex flex-wrap gap-3"><label className="min-w-0 flex-1"><span className="sr-only">ค้นหาออเดอร์</span><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="ค้นหาเลขออเดอร์ ชื่อลูกค้า สินค้า หรือเลขพัสดุ" className="w-full rounded-lg border border-slate-200 bg-white px-4 py-3 text-sm"/></label><label><span className="sr-only">กรองสถานะ</span><select value={status} onChange={e=>setStatus(e.target.value)} className="rounded-lg border border-slate-200 bg-white px-4 py-3 text-sm"><option value="all">ทุกสถานะ</option><option value="waiting">รอชำระเงิน</option><option value="new">รอดำเนินการ</option><option value="preparing">กำลังเตรียมสินค้า</option><option value="shipped">จัดส่งแล้ว</option><option value="completed">เสร็จสิ้น</option></select></label></div><p className="mb-4 text-xs text-slate-500">{rows.length} รายการ · ค้นหาและกรองเฉพาะข้อมูลในหน้านี้</p>
  <div className="overflow-x-auto rounded-xl border border-slate-200 bg-white"><table className="w-full min-w-[850px] text-left text-sm"><thead className="border-b border-slate-200 bg-slate-50 text-xs font-medium text-slate-500"><tr>{['ลำดับ','เลขคำสั่งซื้อ / สินค้า','ผู้รับ'].map(h=><th key={h} className="px-5 py-5">{h}</th>)}<th className="px-5 py-5"><button onClick={()=>setAscending(!ascending)}>อัปเดตล่าสุด {ascending?'↑':'↓'}</button></th>{['ยอดเงิน','ขนส่ง / เลขพัสดุ','สถานะ'].map(h=><th key={h} className="px-5 py-5">{h}</th>)}</tr></thead><tbody>{rows.map((o,index)=><tr key={o.id} className="border-b border-slate-100 align-top last:border-0 hover:bg-slate-50/70"><td className="px-5 py-6 text-slate-400">{index+1}</td><td className="max-w-[230px] px-5 py-6"><button onClick={()=>setDetail(o.id)} className="break-all text-left text-blue-600 underline-offset-4 hover:underline">{o.id}</button><p className="mt-2 text-xs text-slate-500">{o.product}</p></td><td className="px-5 py-6">{o.name}<p className="mt-1 text-xs text-slate-400">{o.phone}</p></td><td className="whitespace-nowrap px-5 py-6 text-xs">{date(o.updated)}</td><td className="whitespace-nowrap px-5 py-6">{money(o.amount)}</td><td className="px-5 py-6 text-xs">{o.tracking?<><p>ไปรษณีย์ไทย</p><p className="mt-1 font-mono">{o.tracking}</p>{o.trackable&&<Link href={`/tracking/${encodeURIComponent(o.id)}`} className="mt-2 block text-blue-600 underline">ติดตามพัสดุ ↗</Link>}</>:<span className="text-slate-400">ยังไม่ระบุ</span>}</td><td className="px-5 py-6"><span className={`inline-block whitespace-nowrap rounded-full px-3 py-1.5 text-xs ${badges[o.state]}`}>{o.label}</span></td></tr>)}{!rows.length&&<tr><td colSpan={7} className="px-5 py-16 text-center text-slate-400">{base.length?'ไม่พบรายการที่ตรงกับการค้นหา':'ยังไม่มีคำสั่งซื้อในหน้านี้'}</td></tr>}</tbody></table></div>
  {detail&&(()=>{const o=orders.find(item=>item.id===detail)!;return <div className="fixed inset-0 z-50 flex items-center justify-center bg-slate-900/40 p-4" onClick={()=>setDetail(null)}><section role="dialog" aria-modal="true" aria-label="รายละเอียดคำสั่งซื้อ" className="max-h-[90vh] w-full max-w-xl overflow-auto rounded-2xl bg-white p-6" onClick={e=>e.stopPropagation()}><div className="flex justify-between gap-3"><h2 className="text-lg font-semibold">รายละเอียดคำสั่งซื้อ</h2><button autoFocus onClick={()=>setDetail(null)} aria-label="ปิดรายละเอียด" className="rounded-lg border px-3 py-1">ปิด</button></div><p className="mt-3 break-all text-xs text-slate-400">{o.id}</p><h3 className="mt-5 font-medium">{o.product}</h3><p className="mt-2 text-sm">{o.name} · {o.phone}</p><p className="mt-1 break-all text-sm text-slate-500">{o.email}</p><p className="mt-3 text-sm leading-6">{o.address||'ไม่มีที่อยู่จัดส่ง'}</p><p className="mt-4 text-sm">{money(o.amount)} · {o.label}</p>{o.state!=='waiting'&&<form action="/api/admin/orders/status" method="post" className="mt-6 space-y-4 border-t pt-5"><input type="hidden" name="sessionId" value={o.id}/><label className="block text-xs">สถานะจัดส่ง<select name="status" defaultValue={o.state} className="mt-2 block w-full rounded-lg border p-3"><option value="new">รอดำเนินการ</option><option value="preparing">กำลังเตรียมสินค้า</option><option value="shipped">จัดส่งแล้ว</option><option value="completed">เสร็จสิ้น</option></select></label><label className="block text-xs">เลขพัสดุไปรษณีย์ไทย<input name="trackingNumber" defaultValue={o.tracking} maxLength={13} pattern="[A-Za-z]{2}[0-9]{9}[A-Za-z]{2}" placeholder="EA123456789TH" className="mt-2 block w-full rounded-lg border p-3 uppercase"/></label><p className="text-xs text-slate-500">สถานะจัดส่งแล้วและเสร็จสิ้นต้องมีเลขพัสดุ ระบบจะเชื่อมให้ลูกค้าติดตามผ่านบัญชี</p><button className="w-full rounded-lg bg-emerald-600 p-3 text-sm text-white">บันทึกสถานะ</button></form>}</section></div>;})()}</>;
}
