import Link from 'next/link';
import { FigmaImage } from '../components/FigmaImage';

export const metadata = { title: "Help | Valley's Darling" };
export default function HelpPage() {
  return <main className="editorial-page overflow-hidden bg-white text-black">
    <div className="mx-auto max-w-[1440px] px-5 pb-20 pt-12 md:px-[7.5%] md:pt-16">
      <h1 className="brand-script text-right text-[88px] leading-none md:text-[180px]">Help</h1>
      <div className="mt-12 grid gap-16 md:grid-cols-[1fr_2fr] md:gap-12">
        <section id="contact" className="scroll-mt-40 leading-7"><h2 className="text-[22px] font-bold">contact us</h2><a className="block underline" href="https://line.me/R/ti/p/@valleydarley">LINE @valleydarley</a><a className="block break-all underline" href="mailto:valleydarley@gmail.com">email valleydarley@gmail.com</a><a className="block underline" href="https://www.instagram.com/valleydarley/">Instagram @valleydarley</a></section>
        <section id="after-sales" className="scroll-mt-40 space-y-5 leading-7"><h2 className="text-xl font-bold underline">after-sales service (for customers in thailand only)</h2><h3 className="font-bold">damaged on arrival</h3><p>Please record a video while unboxing your order. If your item arrives damaged, send us the video within 1–2 days of delivery and we&apos;ll fix or replace it free of charge.</p><h3 className="font-bold">repairs</h3><p>If your item breaks or a part is lost after use, we can repair it. You only pay for materials and return shipping.</p><h3 className="font-bold">length extension</h3><p>We can make your piece longer. Prices start from 100 THB (materials + return shipping), depending on the material and length you need.</p></section>
      </div>
      <section className="mt-24 max-w-[900px] space-y-5 text-lg leading-relaxed md:mt-36 md:text-xl"><h2 className="font-bold underline">for international customers</h2><h3 className="font-bold">damaged on arrival</h3><p>Contact us within 3 days of delivery with your unboxing video.</p><h3 className="font-bold">repairs</h3><p>Please contact us before sending your piece. Customers pay shipping both ways, materials and any import fees. Use tracked shipping and mark the parcel “returned for repair”. Repairs generally take 7–14 days after receipt.</p></section>
      <section id="shipping" className="mt-24 scroll-mt-40 md:mt-40"><h2 className="brand-script text-center text-[56px] leading-tight md:text-[110px]">Shipping &amp; Return</h2><h3 className="mt-16 text-center text-2xl font-bold">shipping policy</h3><ul className="mt-8 list-disc space-y-5 pl-6 text-lg leading-relaxed md:text-xl"><li>Ready-to-ship items are sent within 1–3 business days after payment. Length-adjusted items take 5–7 business days. Made-to-order items take 4–7 weeks, depending on the design. We do not ship on weekends or public holidays.</li><li>Delivery fees are shown at checkout. Online checkout currently supports Thailand delivery. For international delivery, please contact us for a quote before ordering.</li><li>Once your order is shipped, your tracking details will appear in <Link href="/orders" className="underline">My orders</Link>.</li><li>Please check your delivery address carefully. Contact us if your parcel is delayed or missing.</li></ul>
        <h3 id="returns" className="mt-20 scroll-mt-40 text-center text-2xl font-bold">returns</h3><ul className="mt-8 list-disc space-y-5 pl-6 text-lg leading-relaxed md:text-xl"><li>Returns are accepted within 7 days of delivery. Please contact us before sending anything back.</li><li>Items must be unworn, undamaged and in their original packaging.</li><li>Customers pay return shipping and any applicable import fees. Refunds are made to the original payment method within 7 days after we receive and check your item.</li><li>Original shipping fees, bank fees and exchange rate differences are non-refundable.</li><li>We cannot accept returns on custom-made or length-adjusted items, earrings (for hygiene reasons), and sale items.</li></ul>
      </section>
      <section id="care" className="mt-24 scroll-mt-40 md:mt-40"><h2 className="text-center text-[32px] font-bold">care instruction</h2><FigmaImage src="/images/figma/help-care.png" alt="Jewelry care illustration" className="mx-auto mt-12 aspect-[946/372] max-w-[946px]" crop={{width:'154.44%',height:'490.62%',left:'-30.55%',top:'-98.79%'}} /><div className="mt-16 space-y-6 text-lg leading-relaxed md:text-xl"><h3 className="font-bold">NATURAL BEAD PRODUCTS CARE</h3><p>Avoid contact with cosmetics, creams, sprays, perfumes and detergents. Remove your jewelry before bathing or exercising, and avoid high heat and knocks against hard objects.</p><h3 className="font-bold">how to clean your jewelry</h3><p>Gently wipe your jewelry with a silver polishing cloth after every wear to remove oil and sweat residue.</p><h3 className="font-bold">how to store</h3><p>Keep your jewelry in a fabric pouch or zip-lock bag to prevent scratches. Store it in a dry place away from humidity.</p></div></section>
    </div>
    <section id="size-guide" className="scroll-mt-40"><h2 className="border-y border-black py-4 text-center text-[32px] font-bold">size guide</h2><FigmaImage src="/images/figma/help-necklace-size.png" alt="Necklace length and fit guide" className="mx-auto my-12 aspect-[1334/1667] w-[93%] max-w-[1334px]" /></section>
    <section id="ring-size" className="mx-auto max-w-[1440px] scroll-mt-40 px-[5%]"><h2 className="brand-script mb-12 text-center text-[56px] leading-tight md:text-[96px]">A guide for the Ring</h2><FigmaImage src="/images/figma/help-ring-size.png" alt="Ring sizing chart and measuring instructions" className="aspect-[1291/1474]" crop={{width:'100%',height:'109.5%',left:'0',top:'-9.49%'}} /></section>
    <section className="relative mt-16 min-h-[600px] bg-[#f1e9eb] px-5 py-28 md:py-52"><FigmaImage src="/images/figma/help-ribbon.png" alt="" className="absolute inset-0 opacity-60" crop={{width:'106.72%',height:'107.17%',left:'0',top:'-7.15%'}} /><div className="relative mx-auto max-w-[626px] bg-white/85 p-8 text-center"><h2 className="text-[32px]">Contact us</h2><p className="mt-5 text-xl">Need a little help finding your piece?</p><a href="mailto:valleydarley@gmail.com" className="editorial-button mt-8">Email us</a><p className="mt-4 text-sm">Opens your email app. You can attach photos with your message.</p></div></section>
  </main>;
}
