"use client";

import { useState } from "react";
import type { CmsContent } from "../lib/cms";

export function CmsEditor({ initialContent, storageReady }: { initialContent: CmsContent; storageReady: boolean }) {
  const [content, setContent] = useState(initialContent);
  const [section, setSection] = useState<"pages" | "products" | "settings">("pages");
  const [status, setStatus] = useState<"idle" | "saving" | "saved" | "error">("idle");
  const save = async () => { setStatus("saving"); const response = await fetch("/api/admin/content", { method: "PUT", headers: { "Content-Type": "application/json" }, body: JSON.stringify(content) }); if (!response.ok) return setStatus("error"); setContent(await response.json()); setStatus("saved"); };
  const input = "w-full rounded-xl border border-black/10 bg-white px-4 py-3 text-sm outline-none focus:border-black/40";
  const updateProduct = (index: number, values: Partial<CmsContent["products"][number]>) => { const products = [...content.products]; products[index] = { ...products[index], ...values }; setContent({ ...content, products }); };

  return <div className="grid min-h-[calc(100vh-72px)] bg-[#f4f1ec] text-[#211a16] lg:grid-cols-[250px_1fr]">
    <aside className="border-r border-black/10 bg-[#211a16] p-6 text-white lg:p-8"><p className="brand-script text-3xl">Valley&apos;s Darling</p><p className="mt-1 text-[9px] tracking-[.22em] text-white/50">CONTENT STUDIO</p><nav className="mt-12 space-y-2">{[["pages", "เนื้อหาหน้าเว็บ"], ["products", "สินค้าและคอลเลกชัน"], ["settings", "ตั้งค่าเว็บไซต์"]].map(([id, label]) => <button key={id} onClick={() => setSection(id as typeof section)} className={`w-full rounded-xl px-4 py-3 text-left text-sm ${section === id ? "bg-white text-black" : "text-white/70 hover:bg-white/10"}`}>{label}</button>)}</nav><a href="/" target="_blank" className="mt-10 block text-xs text-white/55 underline">เปิดดูเว็บไซต์ ↗</a><form action="/api/admin/logout" method="post" className="mt-6"><button className="text-xs text-white/55 underline">ออกจากระบบแอดมิน</button></form></aside>
    <main className="p-5 md:p-10 lg:p-14"><div className="mx-auto max-w-5xl">
      <div className="flex flex-wrap items-start justify-between gap-4"><div><p className="text-[10px] tracking-[.24em] text-black/40">ADMIN / CMS</p><h1 className="mt-2 font-serif text-4xl">จัดการเว็บไซต์</h1></div><button onClick={save} disabled={status === "saving" || !storageReady} className="rounded-full bg-black px-6 py-3 text-xs text-white disabled:opacity-35">{status === "saving" ? "กำลังบันทึก…" : "บันทึกและเผยแพร่"}</button></div>
      {!storageReady && <div className="mt-6 rounded-xl border border-amber-300 bg-amber-50 p-4 text-sm text-amber-900">CMS พร้อมแล้ว แต่ต้องเชื่อม Vercel Blob Storage ก่อนจึงจะบันทึกบน production ได้</div>}{status === "saved" && <p className="mt-5 rounded-xl bg-emerald-50 p-4 text-sm text-emerald-700">บันทึกและเผยแพร่แล้ว</p>}{status === "error" && <p className="mt-5 rounded-xl bg-red-50 p-4 text-sm text-red-700">บันทึกไม่สำเร็จ กรุณาตรวจ Storage และลองใหม่</p>}
      {section === "pages" && <div className="mt-8 space-y-6"><Panel title="หน้าแรก"><Field label="หัวข้อบรรทัดแรก" value={content.home.heading} onChange={v => setContent({ ...content, home: { ...content.home, heading: v } })} input={input} /><Field label="คำตัวเอียง" value={content.home.emphasis} onChange={v => setContent({ ...content, home: { ...content.home, emphasis: v } })} input={input} /><Field label="หัวข้อบรรทัดสุดท้าย" value={content.home.ending} onChange={v => setContent({ ...content, home: { ...content.home, ending: v } })} input={input} /><Area label="คำแนะนำแบรนด์" value={content.home.intro} onChange={v => setContent({ ...content, home: { ...content.home, intro: v } })} input={input} /></Panel><Panel title="Custom Made"><Field label="หัวข้อ" value={content.customMade.heading} onChange={v => setContent({ ...content, customMade: { ...content.customMade, heading: v } })} input={input} /><Area label="รายละเอียด" value={content.customMade.body} onChange={v => setContent({ ...content, customMade: { ...content.customMade, body: v } })} input={input} /></Panel><Panel title="Contact"><Field label="หัวข้อ" value={content.contact.heading} onChange={v => setContent({ ...content, contact: { ...content.contact, heading: v } })} input={input} /><Area label="รายละเอียด" value={content.contact.body} onChange={v => setContent({ ...content, contact: { ...content.contact, body: v } })} input={input} /></Panel></div>}
      {section === "products" && <div className="mt-8 space-y-4">{content.products.map((product, index) => <div key={product.id} className="grid gap-3 rounded-2xl bg-white p-5 shadow-sm md:grid-cols-[1fr_1fr_auto] md:items-end"><Field label={`ชื่อสินค้า ${index + 1}`} value={product.name} onChange={v => updateProduct(index, { name: v })} input={input} /><Field label="รูปภาพ / URL" value={product.image} onChange={v => updateProduct(index, { image: v })} input={input} /><label className="flex h-11 items-center gap-2 text-xs"><input type="checkbox" checked={product.published} onChange={e => updateProduct(index, { published: e.target.checked })} /> เผยแพร่</label></div>)}</div>}
      {section === "settings" && <div className="mt-8"><Panel title="ข้อมูลเว็บไซต์"><Field label="ชื่อแบรนด์" value={content.site.brand} onChange={v => setContent({ ...content, site: { ...content.site, brand: v } })} input={input} /><Area label="คำอธิบายเว็บไซต์" value={content.site.description} onChange={v => setContent({ ...content, site: { ...content.site, description: v } })} input={input} /><Field label="ลิงก์ติดต่อ" value={content.contact.url} onChange={v => setContent({ ...content, contact: { ...content.contact, url: v } })} input={input} /></Panel></div>}
    </div></main>
  </div>;
}

function Panel({ title, children }: { title: string; children: React.ReactNode }) { return <section className="rounded-2xl bg-white p-5 shadow-sm md:p-7"><h2 className="mb-5 font-serif text-2xl">{title}</h2><div className="grid gap-4 md:grid-cols-2">{children}</div></section>; }
function Field({ label, value, onChange, input }: { label: string; value: string; onChange: (value: string) => void; input: string }) { return <label className="block text-xs text-black/55"><span className="mb-2 block">{label}</span><input className={input} value={value} onChange={e => onChange(e.target.value)} /></label>; }
function Area({ label, value, onChange, input }: { label: string; value: string; onChange: (value: string) => void; input: string }) { return <label className="block text-xs text-black/55 md:col-span-2"><span className="mb-2 block">{label}</span><textarea rows={4} className={input} value={value} onChange={e => onChange(e.target.value)} /></label>; }
