import Link from 'next/link';
import { redirect } from 'next/navigation';
import { adminSession } from '../../lib/admin-auth';
import { getLinePage, lineShoppingReady, lineTrackingUrl, type LineOrder, type LineProduct } from '../../lib/line-shopping';

export const dynamic = 'force-dynamic';
const money = (value: number) => Number.isFinite(value) ? new Intl.NumberFormat('th-TH', { style: 'currency', currency: 'THB' }).format(value) : '—';
const date = (value: string) => Number.isFinite(Date.parse(value)) ? new Date(value).toLocaleString('th-TH', { timeZone: 'Asia/Bangkok' }) : '—';
const labels: Record<string, string> = { PAID: 'ชำระแล้ว', PENDING: 'รอดำเนินการ', NO_PAYMENT: 'ยังไม่ชำระ', REFUND: 'คืนเงินแล้ว', FINALIZED: 'ยืนยันออร์เดอร์', COMPLETED: 'สำเร็จ', CANCELED: 'ยกเลิก', EXPIRED: 'หมดอายุ', NO_SHIPMENT: 'ยังไม่จัดส่ง', SHIPMENT_READY: 'พร้อมส่ง', ON_DELIVERY: 'ระหว่างจัดส่ง', SHIPPED_ALL: 'จัดส่งแล้ว' };

export default async function LineShopping({ searchParams }: { searchParams: Promise<{ page?: string; tab?: string; q?: string }> }) {
  if (!await adminSession()) redirect('/admin/login');
  const params = await searchParams;
  const tab = params.tab === 'products' ? 'products' : 'orders';
  const page = Math.max(1, Math.min(10000, Number.parseInt(params.page || '1', 10) || 1));
  const q = (params.q || '').slice(0, 100);
  let orders: LineOrder[] = []; let products: LineProduct[] = []; let total = 0; let pages = 0; let error = '';
  try {
    if (tab === 'orders') { const result = await getLinePage<LineOrder>('orders', page, q); orders = result.data; total = result.totalRow; pages = result.totalPage; }
    else { const result = await getLinePage<LineProduct>('products', page); products = result.data; total = result.totalRow; pages = result.totalPage; }
  } catch { error = lineShoppingReady() ? 'โหลดข้อมูล LINE SHOPPING ไม่สำเร็จ กรุณารีเฟรชหรือตรวจสิทธิ์ API' : 'ยังไม่ได้ตั้งค่า LINE_SHOPPING_API_KEY บนเซิร์ฟเวอร์'; }
  const href = (p: number) => `/admin/line-shopping?${new URLSearchParams({ tab, page: String(p), ...(q && tab === 'orders' ? { q } : {}) })}`;
  return <section className="p-4 md:p-8">
    <div className="mb-6 flex flex-wrap items-center justify-between gap-4"><div><p className="text-xs tracking-widest text-slate-400">E-COMMERCE / LINE SHOPPING</p><h1 className="mt-2 text-2xl font-semibold">ร้าน LINE SHOPPING</h1></div><a href={href(page)} className="rounded-lg border bg-white px-4 py-3 text-sm">รีเฟรชข้อมูล ↻</a></div>
    <div className={`rounded-xl p-4 text-sm leading-6 ${error ? 'bg-red-50 text-red-800' : 'bg-emerald-50 text-emerald-800'}`} role={error ? 'alert' : 'status'}>{error || 'เชื่อมต่อแล้ว · ดึงข้อมูลล่าสุดจาก LINE SHOPPING เมื่อเปิดหรือรีเฟรชหน้านี้'}<p className="mt-1 text-xs">อ่านข้อมูลเท่านั้น ไม่แก้ราคา สต็อก ออร์เดอร์ หรือแชทใน LINE · เลขพัสดุแสดงเมื่อบันทึกใน LINE แล้ว</p></div>
    <nav className="my-6 flex gap-3" aria-label="ข้อมูล LINE SHOPPING">{[['orders','คำสั่งซื้อ / จัดส่ง'],['products','สินค้า / สต็อก']].map(([key,label])=><Link key={key} href={`/admin/line-shopping?tab=${key}`} aria-current={tab===key?'page':undefined} className={`rounded-lg px-4 py-3 text-sm ${tab===key?'bg-emerald-600 text-white':'border bg-white'}`}>{label}</Link>)}</nav>
    {tab==='orders'&&<form className="mb-5 flex gap-2" method="get"><input type="hidden" name="tab" value="orders"/><input name="q" defaultValue={q} maxLength={100} aria-label="ค้นหาชื่อลูกค้าหรือเลขคำสั่งซื้อ" placeholder="ค้นหาชื่อลูกค้าหรือเลขคำสั่งซื้อ" className="min-w-0 flex-1 rounded-lg border bg-white px-4 py-3 text-sm"/><button className="rounded-lg bg-slate-800 px-5 text-sm text-white">ค้นหา</button></form>}
    {!error&&<><p className="mb-4 text-sm text-slate-500">{total.toLocaleString('th-TH')} {tab==='orders'?'คำสั่งซื้อ':'สินค้า'} · หน้า {page} / {Math.max(1,pages)}</p>
    {tab==='orders'?<div className="overflow-x-auto rounded-xl border bg-white"><table className="w-full min-w-[900px] text-left text-sm"><thead className="border-b bg-slate-50 text-xs text-slate-500"><tr>{['เลขคำสั่งซื้อ / สถานะ','ผู้รับ','อัปเดตล่าสุด','ยอดรวม / ชำระเงิน','ขนส่ง / เลขพัสดุ','สถานะจัดส่ง'].map(h=><th key={h} className="p-4 font-medium">{h}</th>)}</tr></thead><tbody>{orders.map(o=>{ const trackingUrl=lineTrackingUrl(o.shipmentDetail?.trackingUrl); const a=o.shippingAddress; return <tr key={o.orderNumber} className="border-b align-top last:border-0"><td className="p-4 font-medium text-blue-600">{o.orderNumber}<p className="mt-2 text-xs font-normal text-slate-500">{labels[o.orderStatus]||o.orderStatus}</p></td><td className="max-w-[240px] p-4">{a?.recipientName||'ยังไม่ระบุผู้รับ'}<details className="mt-2 text-xs text-slate-500"><summary className="cursor-pointer">ข้อมูลจัดส่ง</summary><p className="mt-2 leading-6">{[a?.address,a?.subDistrict,a?.district,a?.province,a?.postalCode].filter(Boolean).join(' ')}<br/>{a?.phoneNumber}<br/>{a?.email}</p></details></td><td className="p-4 text-xs">{date(o.lastUpdatedAt)}</td><td className="p-4">{money(o.totalPrice)}<p className="mt-2 text-xs text-slate-500">{labels[o.paymentStatus]||o.paymentStatus}</p></td><td className="p-4">{o.shipmentDetail?.shipmentCompanyNameTh||o.shipmentDetail?.name||'—'}<p className="mt-2 font-mono text-xs">{o.shipmentDetail?.trackingNumber||'ยังไม่มีเลขพัสดุ'}</p>{trackingUrl&&<a href={trackingUrl} target="_blank" rel="noopener noreferrer" className="mt-2 inline-block text-xs text-blue-600 underline">ติดตามกับขนส่ง ↗</a>}{o.shipmentDetail?.isAutoTracking&&<p className="mt-2 text-xs text-emerald-600">Auto-tracking จาก LINE</p>}</td><td className="p-4"><span className="inline-block rounded-full bg-slate-100 px-3 py-1 text-xs">{labels[o.shipmentStatus]||o.shipmentStatus}</span></td></tr>})}{orders.length===0&&<tr><td colSpan={6} className="p-10 text-center text-slate-500">ไม่พบคำสั่งซื้อ</td></tr>}</tbody></table></div>:<div className="grid grid-cols-2 gap-4 xl:grid-cols-4">{products.map(p=><article key={p.id} className="overflow-hidden rounded-xl border bg-white">{lineTrackingUrl(p.imageUrls?.[0])&&<img src={p.imageUrls[0]} alt={p.name} className="aspect-square w-full object-cover" loading="lazy" referrerPolicy="no-referrer"/>}<div className="p-4"><h2 className="text-sm font-medium">{p.name}</h2><p className="mt-2 text-xs text-slate-400">ID {p.id} · {p.isDisplay?'เปิดขาย':'ซ่อน'}</p><div className="mt-3 space-y-2">{p.variants?.map(v=><p key={v.id} className="text-xs text-slate-500">{v.sku||`ตัวเลือก ${v.id}`} · {money(v.discountedPrice ?? v.price)} · คงเหลือ {v.availableNumber}</p>)}</div></div></article>)}</div>}
    <div className="mt-6 flex justify-between text-sm">{page>1?<Link href={href(page-1)} className="rounded-lg border bg-white px-4 py-3">← ก่อนหน้า</Link>:<span/>}{page<pages&&<Link href={href(page+1)} className="rounded-lg bg-emerald-600 px-4 py-3 text-white">ถัดไป →</Link>}</div></>}
  </section>;
}
